# Site settings
title: Giuseppe Concialdi
description: Machine Learning Engineer focused on LLMs and Generative AI
email: giuseppe.concialdi@gmail.com
baseurl: ""
url: "https://giuseppeconcialdi.com"

# Author settings
author:
  name: Giuseppe Concialdi
  description: Machine Learning Engineer focused on LLMs and Generative AI
  location: New York, NY

# Navigation
navigation:
  - title: Home
    url: /
  - title: Writing
    url: /writing/
  - title: AI News
    url: /ai-news/
  - title: About
    url: /about/

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:title/
  ai_news:
    output: true
    permalink: /ai-news/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Giuseppe Concialdi
  - scope:
      path: ""
      type: "ai_news"
    values:
      layout: "ai_news"
      author: AI News Bot

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
