name: Daily AI News

on:
  schedule:
    - cron: '30 12 * * *'  # 8:30 AM EST daily
  workflow_dispatch:
    inputs:
      date:
        description: 'Date (YYYY-MM-DD)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  fetch-ai-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    
    - name: Fetch AI news and generate digest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        if [ -n "${{ github.event.inputs.date }}" ]; then
          python scripts/fetch_ai_news.py --date "${{ github.event.inputs.date }}"
        else
          python scripts/fetch_ai_news.py
        fi
    
    - name: Configure Git
      run: |
        git config --local user.email "giuseppe.concialdi@gmail.com"
        git config --local user.name "AI News Bot"
    
    - name: Commit and push changes
      run: |
        echo "Checking for new files..."
        ls -la _ai_news/ || echo "No _ai_news directory found"
        git add _ai_news/
        if git diff --staged --quiet; then
          echo "No new news digest to commit"
        else
          echo "Changes detected, committing..."
          git commit -m "AI news digest $(date '+%Y-%m-%d')"
          git push
          echo "✅ Done"
        fi
        echo "News fetch job completed successfully"

# Build and deployment will be handled by jekyll.yml workflow when we push changes