name: Daily AI News

on:
  schedule:
    - cron: '15 13 * * *'  # 9:15 AM EST daily
  workflow_dispatch:
    inputs:
      date:
        description: 'Date (YYYY-MM-DD)'
        required: false
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fetch-ai-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    
    - name: Fetch AI news and generate digest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd scripts
        if [ -n "${{ github.event.inputs.date }}" ]; then
          python fetch_ai_news.py --date "${{ github.event.inputs.date }}"
        else
          python fetch_ai_news.py
        fi
    
    - name: Configure Git
      run: |
        git config --local user.email "giuseppe.concialdi@gmail.com"
        git config --local user.name "AI News Bot"
    
    - name: Commit and push changes
      run: |
        git add _ai_news/
        if git diff --staged --quiet; then
          echo "No new news digest to commit"
        else
          git commit -m "AI news digest $(date -d yesterday '+%Y-%m-%d')"
          git push
          echo "✅ Done"
        fi
    
    - name: Setup Pages
      if: success()
      uses: actions/configure-pages@v3
    
    - name: Build with Jekyll
      if: success()
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
    
    - name: Upload Pages artifact
      if: success()
      uses: actions/upload-pages-artifact@v3

  deploy:
    if: success()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: fetch-ai-news
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2